kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: node:18.12.1-alpine3.16@sha256:9eff44230b2fdcca57a73b8f908c8029e72d24dd05cac5339c79d3dedf6b208b
    commands:
      - npm ci
      - npm run build

  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: registry.nasvigo.com/v2/rubasace/my-resume
      registry: registry.nasvigo.com/v2
      tags: 1.0.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
trigger:
  event:
    - push