kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: node:20.2.0-alpine3.16@sha256:f9b54b46639a9017b39eba677cf44c8cb96760ca69dadcc1d4cbd1daea753225
    commands:
      - npm ci
      - npm run build

  - name: bake
    image: plugins/docker@sha256:4e482ef91fb2695d658a85c60772d7f75f931e0883e23ec0954f0bc17ccc0663
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: registry.nasvigo.com/v2/rubasace/my-resume
      registry: registry.nasvigo.com/v2
      tags: 1.0.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
trigger:
  event:
    - push